/* SPDX-License-Identifier: GPL-3.0-only */
/* generated by tools/builder/cpu_costs.py from tests/cpu_baseline.txt (tests/regress.c) and the emulator's
 * scale in tools/builder/costs.json (target instructions per host instruction: 104 %; per engine:
 * ACID 111 %, FM6 118 %, X0X 122 %): do not edit. The CPU guard's model (cpuguard.c), target instructions a sample. Engines with
 * no baseline entry take the largest measured voice: SLICE, PHYS, CZ */
#pragma once
#define CG_COST_BASE 120u      /* the idle mix */
#define CG_COST_DRUMS 490u     /* the drum groove on top of it */
#define CG_NVCOST 14u
static const uint16_t CG_VCOST[CG_NVCOST] = {160, 126, 135, 87, 76, 242, 158, 119, 116, 232, 465, 465, 496, 465};   /* a sounding voice, by engine UID: ANALOG DIGITAL PHASE LOFI SAMPLE VOICE TRIO WHEEL GRAIN FM6 SLICE PHYS ACID CZ */
#define CG_X0X_SHARED 220u    /* while any X0X channel sounds (their mix) */
static const uint16_t CG_X0X[24] = {204, 234, 182, 197, 198, 186, 168, 85, 83, 2, 2, 159, 212, 151, 158, 157, 192, 99, 97, 144, 176, 227, 259, 479};   /* a sounding X0X channel (drum_x0x.c: the 909's voices, the 808's lanes) */
#define CG_COST_TCOMP 52u     /* a part's COMP insert while it runs (fx.c tcomp_run) */
#define CG_COST_DBDIST 134u    /* the drum bus's DIST while it runs (fx.c dbus_dist_run) */
#define CG_COST_DBCOMP 64u    /* the drum bus's COMP while it runs (fx.c dbus_comp_run) */
#define CG_COST_DVDIST 106u    /* a drum voice's DIST while it runs (fx.c dins_post) */
#define CG_COST_DVCOMP 127u    /* a drum voice's COMP while it runs (fx.c dins_post) */
