# SPDX-License-Identifier: GPL-3.0-only
"""The CPU guard's cost model (CPU_GUARD, firmware/src/cpuguard.c), generated from measured data, never hand-tuned.

Inputs:
  tests/cpu_baseline.txt   the host CPU baseline tests/regress.c writes (BUDGET_UPDATE=1): instructions per sample
                           of each engine x preset with 8 notes held (VOICE 4, ACID 1: its voices), of the idle mix
                           and of the idle mix with the drum groove
  tools/builder/costs.json "cpu": the target's instructions per host instruction, per engine where measured
                           ("scale_pct", "engine_pct"), fitted in the emulator (docs/CPU-GUARD.md, "Calibration")
Output: firmware/src/cpuguard_costs.h (target instructions a sample):
  CG_COST_BASE    the idle mix (buses, master, the parts' fixed work, the sequencer)
  CG_COST_DRUMS   the drum groove on top of it (any drum voice sounding)
  CG_VCOST[uid]   one sounding voice of each engine (by engine UID, registry.h ENGINE_LIST): the median over the
                  engine's presets of (preset - idle) / voices; an engine with no baseline entry (not built when
                  the baseline was taken) gets the largest measured one (an estimate errs high there)

  python3 tools/builder/cpu_costs.py            write the header
  python3 tools/builder/cpu_costs.py --check    exit 1 when the header is not what the inputs give (the tests)"""
import json
import re
import statistics
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
BASELINE = ROOT / "tests" / "cpu_baseline.txt"
COSTS = ROOT / "tools" / "builder" / "costs.json"
REGISTRY_H = ROOT / "firmware" / "src" / "registry.h"
HEADER = ROOT / "firmware" / "src" / "cpuguard_costs.h"
NOTES = {"VOICE": 4, "ACID": 1}          # voices the regress CPU job sounds (8 notes held; its engine's cap)


def engines():
    """[(uid, list name)] of the build's engine list (registry.h, the FELUCCA_ANALOG2 one: the shipped list)"""
    text = REGISTRY_H.read_text()
    block = text[text.index("#if FELUCCA_ANALOG2"):text.index("#else", text.index("#if FELUCCA_ANALOG2"))]
    return [(int(u), s) for u, s in re.findall(r'X\((\d+),\s*\w+,\s*\d+,\s*"([^"]+)"\)', block)]


def baseline(path=BASELINE):
    out = {}
    for ln in Path(path).read_text().splitlines():
        m = re.fullmatch(r"cpu/(\S+)/(\S+)\s+(\d+)", ln.strip())
        if m:
            out.setdefault(m.group(1), {})[m.group(2)] = int(m.group(3))
    return out


def scales(path=COSTS):
    try:
        cpu = json.loads(Path(path).read_text()).get("cpu", {})
    except (OSError, ValueError):
        cpu = {}
    return int(cpu.get("scale_pct", 100)), {k: int(v) for k, v in cpu.get("engine_pct", {}).items()}


def model(base=None, sc=None):
    """-> dict: base, drums, vcost (list by UID), names, source notes"""
    b = baseline() if base is None else base
    scale, eng_pct = scales() if sc is None else sc
    idle = b["mix"]["idle"]
    drums = b["mix"]["idle_drums"] - idle
    names = engines()
    per = {}
    for _, name in names:
        if name in b:
            per[name] = statistics.median((c - idle) / NOTES.get(name, 8) for c in b[name].values())
    top = max(per.values())

    def tgt(host, name=None):
        return max(1, round(host * eng_pct.get(name, scale) / 100))
    vcost = [tgt(per.get(name, top), name) for _, name in names]
    return {"base": tgt(idle), "drums": tgt(drums), "vcost": vcost, "names": [n for _, n in names],
            "measured": sorted(per), "scale": scale, "engine_pct": eng_pct}


def header(m):
    rows = ", ".join(f"{c}" for c in m["vcost"])
    gone = [n for n in m["names"] if n not in m["measured"]]
    pct = ", ".join(f"{k} {v} %" for k, v in sorted(m["engine_pct"].items())) or "none"
    return "\n".join([
        "/* SPDX-License-Identifier: GPL-3.0-only */",
        "/* generated by tools/builder/cpu_costs.py from tests/cpu_baseline.txt (tests/regress.c) and the emulator's",
        f" * scale in tools/builder/costs.json (target instructions per host instruction: {m['scale']} %; per engine:",
        f" * {pct}): do not edit. The CPU guard's model (cpuguard.c), target instructions a sample. Engines with",
        f" * no baseline entry take the largest measured voice: {', '.join(gone) or 'none'} */",
        "#pragma once",
        f"#define CG_COST_BASE {m['base']}u      /* the idle mix */",
        f"#define CG_COST_DRUMS {m['drums']}u     /* the drum groove on top of it */",
        f"#define CG_NVCOST {len(m['vcost'])}u",
        "static const uint16_t CG_VCOST[CG_NVCOST] = {" + rows + "};   /* a sounding voice, by engine UID: "
        + " ".join(m["names"]) + " */",
        ""])


def main(argv):
    text = header(model())
    if "--check" in argv:
        ok = HEADER.exists() and HEADER.read_text() == text
        print(f"cpu_costs: {HEADER.relative_to(ROOT)} {'matches' if ok else 'is NOT what'} tests/cpu_baseline.txt "
              f"{'and costs.json' if ok else 'and costs.json give: python3 tools/builder/cpu_costs.py'}")
        return 0 if ok else 1
    HEADER.write_text(text)
    print(f"cpu_costs: wrote {HEADER.relative_to(ROOT)}")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
