/* SPDX-License-Identifier: GPL-3.0-only */
/* generated by tools/builder/cpu_costs.py from tests/cpu_baseline.txt (tests/regress.c) and the emulator's
 * scale in tools/builder/costs.json (target instructions per host instruction: 104 %; per engine:
 * ACID 111 %, FM6 118 %): do not edit. The CPU guard's model (cpuguard.c), target instructions a sample. Engines with
 * no baseline entry take the largest measured voice: SLICE, PHYS, CZ */
#pragma once
#define CG_COST_BASE 122u      /* the idle mix */
#define CG_COST_DRUMS 488u     /* the drum groove on top of it */
#define CG_NVCOST 14u
static const uint16_t CG_VCOST[CG_NVCOST] = {159, 122, 135, 86, 76, 242, 158, 118, 116, 232, 463, 463, 494, 463};   /* a sounding voice, by engine UID: ANALOG DIGITAL PHASE LOFI SAMPLE VOICE TRIO WHEEL GRAIN FM6 SLICE PHYS ACID CZ */
