/* SPDX-License-Identifier: GPL-3.0-only */
/* generated by tools/builder/cpu_costs.py from tests/cpu_baseline.txt (tests/regress.c) and the emulator's
 * scale in tools/builder/costs.json (target instructions per host instruction: 104 %; per engine:
 * ACID 111 %, FM6 118 %): do not edit. The CPU guard's model (cpuguard.c), target instructions a sample. Engines with
 * no baseline entry take the largest measured voice: SLICE, PHYS */
#pragma once
#define CG_COST_BASE 120u      /* the idle mix */
#define CG_COST_DRUMS 490u     /* the drum groove on top of it */
#define CG_NVCOST 13u
static const uint16_t CG_VCOST[CG_NVCOST] = {160, 126, 135, 87, 76, 242, 158, 119, 116, 232, 465, 465, 496};   /* a sounding voice, by engine UID: ANALOG DIGITAL PHASE LOFI SAMPLE VOICE TRIO WHEEL GRAIN FM6 SLICE PHYS ACID */
