/* generated by tools/level_presets.py: the level trim of each factory preset, 1/2 dB */
#pragma once
#define PT_ENGINES 10u
#define PT_MAX 16u
static const int8_t PRESET_TRIM[PT_ENGINES][PT_MAX] = {
    {/* 0.0 808 BOOM */ -9, /* 0.1 808 DIRTY */ -8, /* 0.2 SUB BASS */ -10, /* 0.3 808 SLIDE */ -8, /* 0.4 ACID 303 */ 21, /* 0.5 PLUGG BASS */ -6, /* 0.6 REESE */ 3, /* 0.7 WOBBLE */ 6, /* 0.8 FUNK BASS */ 16, /* 0.9 G-FUNK LD */ -10, /* 0.10 TRAP PLUCK */ 23, /* 0.11 SYN BRASS */ 23, /* 0.12 SUPERSAW */ -18, /* 0.13 WARM PAD */ -7, /* 0.14 DARK STR */ -4, /* 0.15 ATMOS PAD */ -9},
    {/* 1.0 RHODES */ 23, /* 1.1 DX RHODES */ 15, /* 1.2 WURLI */ 23, /* 1.3 CLAV */ 15, /* 1.4 M1 PIANO */ 17, /* 1.5 AFRO KEYS */ 18, /* 1.6 TRAP BELL */ 6, /* 1.7 MUSIC BOX */ 7, /* 1.8 MARIMBA */ 23, /* 1.9 KALIMBA */ 23, /* 1.10 PLUGG BELL */ 16, /* 1.11 GLASS PAD */ -18, /* 1.12 FM BASS */ 11},
    {/* 2.0 CZ BASS */ 23, /* 2.1 SOFT KEYS */ 23, /* 2.2 CZ STRING */ -21, /* 2.3 RESO PLUCK */ 19, /* 2.4 CZ BRASS */ 8},
    {/* 3.0 GAME LEAD */ -4, /* 3.1 GB BASS */ 15, /* 3.2 8BIT ARP */ -5},
    {/* 4.0 GRAND PNO */ 17, /* 4.1 UP BASS */ 2, /* 4.2 VIBES */ -4, /* 4.3 HORN STAB */ -11, /* 4.4 STRING STB */ 23, /* 4.5 LOFI FLUTE */ -1, /* 4.6 SCRATCH */ -3, /* 4.7 GM KIT */ 0, /* 4.8 DUSTY PNO */ 19, /* 4.9 LOFI KEYS */ 11, /* 4.10 DEEP BASS */ 23},
    {/* 5.0 CHOIR AAH */ -26, /* 5.1 SOUL OOH */ -24, /* 5.2 TALKBOX */ -11, /* 5.3 WOW BASS */ 3},
    {/* 6.0 FAT BASS */ 20, /* 6.1 MIN STAB */ 23, /* 6.2 MIN7 STAB */ 23, /* 6.3 RAVE STAB */ 21, /* 6.4 DUB CHORD */ 23, /* 6.5 SAW PAD */ -11, /* 6.6 SYNC LEAD */ -3, /* 6.7 HOOVER */ 3},
    {/* 7.0 SOUL ORGAN */ -14, /* 7.1 GOSPEL */ -10, /* 7.2 JAZZ ORGAN */ -8, /* 7.3 DIRTY B3 */ -15, /* 7.4 HOUSE ORGN */ -7},
    {/* 8.0 LOFI CLOUD */ 4, /* 8.1 VIBE HAZE */ 2, /* 8.2 FLUTE DUST */ -1},
    {/* 9.0 SUPER LEAD */ 4, /* 9.1 SUPER PAD */ -6, /* 9.2 SUPER CHRD */ 21, /* 9.3 SUPER PLCK */ 23, /* 9.4 HOOVER SAW */ 1},
};
