#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The one-line parameter help (builder item PARAM_HELP): tools/param_help.json -> the firmware's header and the
web editor's copy (run by tools/build.py).

  gen_param_help.py OUT.h            the header, and web/editor.html's block brought up to date
  gen_param_help.py --check          exit 1 when web/editor.html's block differs from the table (tests)
  gen_param_help.py --stats          sizes: the strings as they are and with a shared word dictionary

The table (tools/param_help.json): groups, each {"kind": "page" | "eng" | "fm6", "ctx": ..., "if": C condition,
"params": {LABEL: TEXT | {"text": TEXT, "if": C condition}}, "slots": [null | [LABEL, TEXT] | [LABEL, TEXT, cond]]}.
  page  a device page by its title (params.c PAGES), its values by their label; also the live screens' knobs
        (TRACKS, DRUM GRID, DRUM KIT, SONG) and the pages without descriptors (STEP, MOTION, USER ...) by "slots":
        KNOB 1..4, the label is what the screen shows (the device looks them up as "1".."4")
  eng   an engine's EDIT values (P_E0..P_E7, also their mode-dependent labels: engine_t.desc) by engine name
  fm6   the FM6 operator editor (ui_fm6.c) by its page name
Each line fits the top bar: WIDTH_PX pixels of the UI font (Terminus 8x16, assets/fonts/ter-u16n.bdf).

The header: one const string in flash (PH_BLOB), the groups one after the other, each wrapped in its "if" so a
build carries the lines of the features it has: kind byte, context, NUL, then label NUL text NUL ..., an empty
label ends the group; kind 0 ends the table. param_help.c looks a line up as (kind, context, label) -> offset.
The editor's copy (web/editor.html, between the PARAM_HELP markers): every line, whatever a build has (the editor
talks to any firmware): PARAM_HELP = {page: {CTX: {LABEL: TEXT}}, eng: {...}, fm6: {...}}.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLE = ROOT / "tools" / "param_help.json"
EDITOR = ROOT / "web" / "editor.html"
FONT = ROOT / "assets" / "fonts" / "ter-u16n.bdf"
WIDTH_PX = 232                     # the top bar from x 4 to 236 (ui_draw.c draw_head), the live screens' header too
KINDS = {"page": 1, "eng": 2, "fm6": 3}
BEGIN = "/* PARAM_HELP BEGIN: tools/gen_param_help.py from tools/param_help.json (do not edit here) */"
END = "/* PARAM_HELP END */"


def font_widths(path=FONT):
    """code -> advance (BDF DWIDTH; the font's cell width when a glyph has none)"""
    lines = path.read_text(errors="replace").splitlines()
    cw = int(next(l for l in lines if l.startswith("FONTBOUNDINGBOX")).split()[1])
    w, code = {}, None
    for l in lines:
        if l.startswith("ENCODING"):
            code = int(l.split()[1])
            w[code] = cw
        elif l.startswith("DWIDTH") and code is not None:
            w[code] = int(l.split()[1])
    return w


def text_px(s, widths):
    return sum(widths.get(ord(c), widths.get(ord("?"), 8)) for c in s)


def load(path=TABLE):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def entries(group):
    """-> [(device label, shown label, text, condition or "")] of a group"""
    out = []
    for lab, v in group.get("params", {}).items():
        text, cond = (v, "") if isinstance(v, str) else (v["text"], v.get("if", ""))
        out.append((lab, lab, text, cond))
    for i, s in enumerate(group.get("slots", [])):
        if s:
            out.append((str(i + 1), s[0], s[1], s[2] if len(s) > 2 else ""))
    return out


def validate(table, widths=None):
    """-> [problems]: kinds, empty or too wide lines, characters outside printable ASCII, duplicates"""
    widths = widths or font_widths()
    bad, seen = [], set()
    for g in table["groups"]:
        if g.get("kind") not in KINDS:
            bad.append(f"{g.get('ctx')}: kind {g.get('kind')!r}")
        key = (g.get("kind"), g.get("ctx"), g.get("if", ""))
        if key in seen:
            bad.append(f"{g['kind']} {g['ctx']}: twice with the same condition")
        seen.add(key)
        for dev, shown, text, _ in entries(g):
            where = f"{g['kind']} {g['ctx']} / {shown}"
            if not text.strip():
                bad.append(f"{where}: empty")
            if any(not (32 <= ord(c) < 127) for c in text + dev + g["ctx"]):
                bad.append(f"{where}: a character outside printable ASCII")
            if text_px(text, widths) > WIDTH_PX:
                bad.append(f"{where}: {text!r} is {text_px(text, widths)} px (> {WIDTH_PX})")
    return bad


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def header(table):
    """the firmware's header text"""
    out = ["/* generated by tools/gen_param_help.py from tools/param_help.json: do not edit */",
           "/* PH_BLOB: kind (PH_*) context NUL, then label NUL text NUL ..., NUL; kind 0 ends it (param_help.c) */",
           "#define PH_PAGE 1", "#define PH_ENG 2", "#define PH_FM6 3",
           "static const char PH_BLOB[] ="]
    for g in table["groups"]:
        cond = g.get("if", "")
        if cond:
            out.append(f"#if {cond}")
        out.append(f'    "\\{KINDS[g["kind"]]:03o}" {c_str(g["ctx"])} "\\0"')
        for dev, _, text, ec in entries(g):
            if ec:
                out.append(f"#if {ec}")
            out.append(f"        {c_str(dev)} \"\\0\" {c_str(text)} \"\\0\"")
            if ec:
                out.append("#endif")
        out.append('    "\\0"')
        if cond:
            out.append("#endif")
    out.append('    "";   /* (+ the implied NUL: the end) */')
    return "\n".join(out) + "\n"


def editor_table(table):
    """the editor's copy: {kind: {ctx: {shown label: text}}}, every line"""
    t = {k: {} for k in KINDS}
    for g in table["groups"]:
        d = t[g["kind"]].setdefault(g["ctx"], {})
        for _, shown, text, _ in entries(g):
            d.setdefault(shown, text)
    return t


def editor_block(table):
    return f"{BEGIN}\nconst PARAM_HELP = {json.dumps(editor_table(table), separators=(',', ':'), sort_keys=True)};\n{END}"


def editor_sync(table, write=True, path=EDITOR):
    """-> True when web/editor.html holds the table's block (written when write and it did not)"""
    html = path.read_text(encoding="utf-8")
    pat = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)
    if not pat.search(html):
        raise SystemExit(f"gen_param_help: no PARAM_HELP markers in {path}")
    new = pat.sub(lambda m: editor_block(table), html, count=1)
    if new == html:
        return True
    if write:
        path.write_text(new, encoding="utf-8")
    return False


def blob_bytes(table):
    """the bytes PH_BLOB takes with every group in (the largest build)"""
    n = 1
    for g in table["groups"]:
        n += 1 + len(g["ctx"]) + 1 + 1
        n += sum(len(dev) + 1 + len(text) + 1 for dev, _, text, _ in entries(g))
    return n


def dict_stats(table, max_words=96):
    """the same strings with a shared word dictionary (a byte >= 0x80 stands for a word and its space): -> (bytes of
    the strings, bytes of the dictionary, words). The words chosen greedily by the bytes they save"""
    texts = [text for g in table["groups"] for _, _, text, _ in entries(g)]
    from collections import Counter
    cnt = Counter(w for t in texts for w in t.split(" ") if len(w) > 1)
    gain = sorted(((len(w) - 1) * n - (len(w) + 1), w) for w, n in cnt.items())
    words = [w for g, w in reversed(gain) if g > 0][:max_words]
    ws = set(words)
    plain = sum(len(t) + 1 for t in texts)
    packed = 0
    for t in texts:
        tok = t.split(" ")
        packed += sum(1 if w in ws else len(w) for w in tok) + 1          # (+ the NUL)
        packed += sum(1 for w in tok[:-1] if w not in ws)                  # (a word's code holds its space)
    return plain, packed, sum(len(w) + 1 for w in words), len(words)


def main(argv):
    table = load()
    bad = validate(table)
    if bad:
        print("gen_param_help: tools/param_help.json:\n  " + "\n  ".join(bad), file=sys.stderr)
        return 1
    if argv[:1] == ["--check"]:
        if not editor_sync(table, write=False):
            print("gen_param_help: web/editor.html's PARAM_HELP block is out of date (python3 tools/gen_param_help.py "
                  "build/gen/felucca_param_help.h)", file=sys.stderr)
            return 1
        return 0
    if argv[:1] == ["--stats"]:
        plain, packed, dic, nw = dict_stats(table)
        n = sum(len(entries(g)) for g in table["groups"])
        print(f"param help: {n} lines in {len(table['groups'])} groups, blob {blob_bytes(table)} B (all groups); "
              f"texts {plain} B, with a {nw}-word dictionary {packed} B + {dic} B = {packed + dic} B")
        return 0
    if len(argv) != 1:
        print(__doc__, file=sys.stderr)
        return 2
    out = Path(argv[0])
    out.parent.mkdir(parents=True, exist_ok=True)
    text = header(table)
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    wrote = not editor_sync(table)
    print(f"param help: {sum(len(entries(g)) for g in table['groups'])} lines, {blob_bytes(table)} B at most"
          + (" (web/editor.html updated)" if wrote else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
