#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Tables of the DX7 engine (firmware/src/dx7_core.c), computed exactly as msfa computes them at
# start-up (Google music-synthesizer-for-android, Dexed's copy; Apache-2.0): sine, exp2, the
# frequency LUT, the LFO rates and the per-block units at 44.1 kHz with 32-sample blocks.
# Doubles here are the C doubles there, so the tables come out bit for bit the same.
#   gen_dx7_tables.py OUT.h
import math
import sys

FS = 44100.0
LG_N = 5                      # SLOOP renders 32-sample blocks (msfa: 64)
N = 1 << LG_N


def sin_table():
    """sin.cc Sin::init (SIN_LG_N_SAMPLES 10): values only, entry 1024 = 0 (the wrap); not emitted (the
    firmware makes it the same way: dx7_tables_init), kept as the reference"""
    n = 1024
    dphase = 2 * math.pi / n
    c = math.floor(math.cos(dphase) * (1 << 30) + 0.5)
    s = math.floor(math.sin(dphase) * (1 << 30) + 0.5)
    r = 1 << 29
    u, v = 1 << 30, 0
    t = [0] * (n + 1)
    for i in range(n // 2):
        t[i] = (v + 32) >> 6
        t[i + n // 2] = -((v + 32) >> 6)
        nt = (u * s + v * c + r) >> 30
        u = (u * c - v * s + r) >> 30
        v = nt
    return t


def exp2_table():
    """exp2.cc Exp2::init (EXP2_LG_N_SAMPLES 10): values only, entry 1024 = 2^31"""
    n = 1024
    inc = math.exp2(1.0 / n) if hasattr(math, "exp2") else 2.0 ** (1.0 / n)
    y = float(1 << 30)
    t = []
    for _ in range(n):
        t.append(math.floor(y + 0.5))
        y *= inc
    t.append(1 << 31)
    return t


def freq_table():
    """freqlut.cc Freqlut::init: 1025 entries"""
    y = float(1 << (24 + 20)) / FS
    inc = math.pow(2, 1.0 / 1024)
    t = []
    for _ in range(1025):
        t.append(math.floor(y + 0.5))
        y *= inc
    return t


LFO_SOURCE = [
    0.062541, 0.125031, 0.312393, 0.437120, 0.624610, 0.750694, 0.936330, 1.125302, 1.249609, 1.436782,
    1.560915, 1.752081, 1.875117, 2.062494, 2.247191, 2.374451, 2.560492, 2.686728, 2.873976, 2.998950,
    3.188013, 3.369840, 3.500175, 3.682224, 3.812065, 4.000800, 4.186202, 4.310716, 4.501260, 4.623209,
    4.814636, 4.930480, 5.121901, 5.315191, 5.434783, 5.617346, 5.750431, 5.946717, 6.062811, 6.248438,
    6.431695, 6.564264, 6.749460, 6.868132, 7.052186, 7.250580, 7.375719, 7.556294, 7.687577, 7.877738,
    7.993605, 8.181967, 8.372405, 8.504848, 8.685079, 8.810573, 8.986341, 9.122423, 9.300595, 9.500285,
    9.607994, 9.798158, 9.950249, 10.117361, 11.251125, 11.384335, 12.562814, 13.676149, 13.904338,
    15.092062, 16.366612, 16.638935, 17.869907, 19.193858, 19.425019, 20.833333, 21.034918, 22.502250,
    24.003841, 24.260068, 25.746653, 27.173913, 27.578599, 29.052876, 30.693677, 31.191516, 32.658393,
    34.317090, 34.674064, 36.416606, 38.197097, 38.550501, 40.387722, 40.749796, 42.625746, 44.326241,
    44.883303, 46.772685, 48.590865, 49.261084,
]


def lfo_delta():
    """lfo.cc Lfo::reset: delta_ = lfoSource[rate] * lforatio_ (uint32 lforatio_, then double product)"""
    lforatio = int(4437500000.0 * N / FS) & 0xFFFFFFFF
    return [int(x * lforatio) & 0xFFFFFFFF for x in LFO_SOURCE]


def detune_q8():
    """dx7note.cc osc_freq (Dexed): detuneRatio * logfreq per DETUNE step, Q8, per MIDI note"""
    base, step = 50857777, (1 << 24) // 12
    out = []
    for mn in range(128):
        lf = base + step * mn
        r = 0.0209 * math.exp(-0.396 * (lf / (1 << 24))) / 7
        out.append(int(math.floor(r * lf * 256 + 0.5)))
    return out


def main():
    out = sys.argv[1]
    lfo_unit = int(N * 25190424 / FS + 0.5)
    penv_unit = int(N * (1 << 24) / (21.3 * FS) + 0.5)
    log2e = 1.0 / math.log(2.0)
    am_a = int(round(12.2 * log2e * (1 << 24)))        # Dexed's amp mod: exp(sens / 262144 * 0.07 + 12.2)
    am_b = int(round(0.07 * log2e / 262144 * (1 << 24) * 65536))
    rows = [
        "/* generated by tools/gen_dx7_tables.py: msfa's tables (Apache-2.0), 44.1 kHz, 32-sample blocks */",
        "#pragma once",
        "#include <stdint.h>",
        f"#define DX7_LG_N {LG_N}",
        f"#define DX7_LFO_UNIT {lfo_unit}u",
        f"#define DX7_PENV_UNIT {penv_unit}",
        f"#define DX7_AM_A {am_a}",
        f"#define DX7_AM_B {am_b}",
    ]

    def arr(decl, vals, per=8):
        rows.append(decl + " = {")
        for i in range(0, len(vals), per):
            rows.append("    " + ", ".join(str(v) for v in vals[i:i + per]) + ",")
        rows.append("};")

    # the sine table is made at start-up from these (msfa's integer recurrence: dx7_core.c)
    dphase = 2 * math.pi / 1024
    rows.append(f"#define DX7_SIN_C {math.floor(math.cos(dphase) * (1 << 30) + 0.5)}")
    rows.append(f"#define DX7_SIN_S {math.floor(math.sin(dphase) * (1 << 30) + 0.5)}")
    ex = exp2_table()
    arr("static const uint32_t DX7_EXP2[1025]", [f"{v}u" for v in ex])
    # the frequency LUT from the exp2 table: (exp2[i] K + 2^31) >> 32, + a correction of -1 / 0 / +1 (2 bits)
    fr = freq_table()
    k = int(round(float(1 << 44) / FS / (1 << 30) * (1 << 32)))
    fix = [fr[i] - ((ex[i] * k + (1 << 31)) >> 32) for i in range(1025)]
    if min(fix) < -1 or max(fix) > 1:
        raise SystemExit("gen_dx7_tables: the frequency LUT needs more than a 2-bit correction")
    rows.append(f"#define DX7_FREQ_K {k}u")
    packed = [sum((fix[i + j] + 1) << (2 * j) for j in range(4) if i + j < 1025) for i in range(0, 1025, 4)]
    arr("static const uint8_t DX7_FREQ_FIX[257]", packed, 16)
    arr("static const uint32_t DX7_LFO_DELTA[100]", [f"{v}u" for v in lfo_delta()])
    arr("static const int32_t DX7_DETUNE_Q8[128]", detune_q8())
    arr("static const int32_t DX7_FINE_TAB[100]", [int(math.floor(24204406.323123 * math.log(1 + 0.01 * f) + 0.5))
                                              for f in range(100)])
    with open(out, "w") as f:
        f.write("\n".join(rows) + "\n")
    print(f"dx7 tables: {out}")


if __name__ == "__main__":
    main()
