#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
# The classic DX7 voices for the DX7 engine: a 32-voice bank (.syx, VMEM) -> C (the packed 128-byte
# voices, unpacked when loaded: dx7_core.c dx7_unpack) and their names.
#   gen_dx7_rom.py OUT.h [bank.syx]      (default: assets/dx7/rom1a.syx, see assets/dx7/PROVENANCE.md)
# FELUCCA_DX7_ROM=0 (build.py) leaves the bank out of the firmware: a build to give away can swap in
# self-made voices (another bank here) or none.
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]


def main():
    out = sys.argv[1]
    src = pathlib.Path(sys.argv[2]) if len(sys.argv) > 2 else ROOT / "assets" / "dx7" / "rom1a.syx"
    b = src.read_bytes()
    if len(b) != 4104 or b[:6] != bytes([0xF0, 0x43, 0x00, 0x09, 0x20, 0x00]) or b[-1] != 0xF7:
        raise SystemExit(f"{src}: not a DX7 32-voice bank (VMEM)")
    data = b[6:6 + 4096]
    names = []
    for i in range(32):
        raw = data[i * 128 + 118:i * 128 + 128].decode("ascii", "replace")
        nm = " ".join(raw.split()).upper().replace("\\", "/")
        names.append(nm if nm else f"ROM {i + 1}")
    rows = [f"/* generated by tools/gen_dx7_rom.py from {src.name}: provenance in assets/dx7/PROVENANCE.md */",
            "#pragma once", "#include <stdint.h>", "#define DX7_NROM 32u",
            "static const uint8_t DX7_ROM[32][128] = {"]
    for i in range(32):
        v = data[i * 128:(i + 1) * 128]
        rows.append("    {" + ", ".join(str(x & 0x7F) for x in v) + "},")
    rows.append("};")
    rows.append("#define DX7_ROM_NAMES \\")       # (the engine's VOICE names: a list to append)
    for i in range(0, 32, 4):
        rows.append("    " + " ".join('"' + n.replace('"', "'") + '",' for n in names[i:i + 4]) + " \\")
    rows.append("")
    pathlib.Path(out).write_text("\n".join(rows) + "\n")
    print(f"dx7 rom: {len(names)} voices from {src.name} -> {out}")


if __name__ == "__main__":
    main()
