#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""The colour table (tools/colors.json) as RGB565 for the firmware (run by tools/build.py).

  gen_colors.py OUT.h

One table for the device and the web editor (web/editor.html COLORS, checked equal by web/test_web.mjs):
COL_ENG_<NAME> per engine (the names the UI shows: VOICE, WHEEL...), COL_KIND_<KIND> per drum source kind,
COL_ST_OK / COL_ST_WARN / COL_ST_ERR (status: green, amber, red) and COL_OTHER. Colour carries meaning only.
"""
import json
import re
import sys
from pathlib import Path

TABLE = Path(__file__).resolve().parent / "colors.json"


def rgb565(hexcol):
    m = re.fullmatch(r"#([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})", hexcol)
    if not m:
        raise SystemExit(f"gen_colors: {hexcol!r} is not #rrggbb")
    r, g, b = (int(x, 16) for x in m.groups())
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)


def ident(name):
    return re.sub(r"[^A-Z0-9]", "_", name.upper())


def header(t):
    out = ["/* generated by tools/gen_colors.py from tools/colors.json: do not edit */",
           "#ifndef FELUCCA_COLORS_H", "#define FELUCCA_COLORS_H"]
    for group, prefix in (("engines", "COL_ENG_"), ("kinds", "COL_KIND_"), ("status", "COL_ST_")):
        for name, c in t[group].items():
            out.append(f"#define {prefix}{ident(name)} 0x{rgb565(c):04X}u   /* {c} */")
    out.append(f"#define COL_OTHER 0x{rgb565(t['other']):04X}u   /* {t['other']} */")
    out.append("#endif")
    return "\n".join(out) + "\n"


def main():
    if len(sys.argv) != 2:
        raise SystemExit(__doc__)
    text = header(json.loads(TABLE.read_text()))
    out = Path(sys.argv[1])
    if not out.exists() or out.read_text() != text:
        out.write_text(text)
    print(f"colors: {text.count('#define') - 1} RGB565 colours -> {out.name}")


if __name__ == "__main__":
    main()
