# SPDX-License-Identifier: GPL-3.0-only
"""One FM-1 emulator session for the emulator smoke checks (tests/emu/run.py; BUILDING.md, Tests).

The session runs tests/emu/drv (a line-driven driver on the emulator's library, fm1_emu) and keeps it running: a
check drives the panel (keys, knobs), records the audio, reads the firmware's own state through the ELF's symbols
(felucca_dbg, the sequencer, the FX slots) and the serial NOR, and seeds or reads the flash state.

The emulator: EMU_DIR (a rust-emulator directory), else FM1_EMU or EMU_REPO when they name a local checkout, else the
one tools/emu.py uses (emulator/fm1-emulator; in a git worktree the main checkout's), cloned there when missing. The
driver is built into build/emu-drv/ (cargo; a minute the first time).

The emulator picks a flash state by the package's FILE NAME (its family: flash_state.rs family()), so a check
copies the package and its ELF under one fixed name, emucheck.fwsc, into its own directory (build/emu-check/<check>/)
and keeps the state there (state/emucheck.nor and .index)."""
import os
import shutil
import struct
import subprocess
import sys
import threading
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "tools"))
FAMILY = "emucheck"                         # the package's name in a check directory: its flash state's name
NOR_SIZE = 0x100000
SECTOR = 4096
STATE_FORMAT = "fm1-emu flash state 1"
HALF_US = 256 * 1000000 // 44100            # one audio DMA half (256 frames at 44.1 kHz): 5804 us
DBG = ("magic", "halves", "max_us", "nested", "in_audio", "late", "timer_irqs", "ui_frames", "last_us", "cpu_q8",
       "boots")                             # felucca_dbg's first words (hal: the debug block)


class EmuError(Exception):
    pass


def emulator_dir():
    """-> the rust-emulator directory the checks build against"""
    if os.environ.get("EMU_DIR"):
        return Path(os.environ["EMU_DIR"]).expanduser()
    for var in ("FM1_EMU", "EMU_REPO"):
        p = Path(os.environ.get(var, "")).expanduser()
        if os.environ.get(var) and (p / "rust-emulator" / "Cargo.toml").exists():
            return p / "rust-emulator"
    import emu                                            # tools/emu.py: the clone `make emu` uses
    clone = emu.clone_dir()
    if not (clone / ".git").exists():
        import shared
        with shared.install_lock(clone.parent, "emulator"):
            emu.ensure_clone(False, env=dict(os.environ, EMU_OFFLINE="1"), clone=clone)
    return clone / "rust-emulator"


def checkout_dir():
    """-> the emulator checkout (the parent of rust-emulator): FM1_EMU for tests/emu_boot_check.py"""
    return emulator_dir().parent


_DRIVER = None


def driver():
    """-> the emu-drv executable, built (cargo, release) into build/emu-drv/ against emulator_dir()"""
    global _DRIVER
    if _DRIVER:
        return _DRIVER
    if not shutil.which("cargo"):
        raise EmuError("the emulator checks need Rust (cargo): https://rustup.rs")
    emu = emulator_dir()
    if not (emu / "Cargo.toml").exists():
        raise EmuError(f"no emulator at {emu}")
    d = ROOT / "build" / "emu-drv"
    d.mkdir(parents=True, exist_ok=True)
    manifest = (
        "# generated by tests/emu/session.py: the driver of the emulator checks, against the emulator at\n"
        f"# {emu}\n[package]\nname = \"emu-drv\"\nversion = \"0.1.0\"\nedition = \"2021\"\nlicense = \"GPL-3.0-only\"\n\n"
        f"[[bin]]\nname = \"emu-drv\"\npath = {str(ROOT / 'tests' / 'emu' / 'drv' / 'main.rs')!r}\n\n"
        f"[dependencies]\nfm1-emu = {{ path = {str(emu)!r} }}\n\n"
        "[profile.release]\nlto = \"thin\"\ncodegen-units = 1\n\n[workspace]\n").replace("'", '"')
    cargo = d / "Cargo.toml"
    if not cargo.exists() or cargo.read_text() != manifest:
        cargo.write_text(manifest)
        if (emu / "Cargo.lock").exists():               # the emulator's own dependency versions
            shutil.copyfile(emu / "Cargo.lock", d / "Cargo.lock")
    p = subprocess.run(["cargo", "build", "-q", "--release", "--manifest-path", str(cargo)], capture_output=True,
                       text=True)
    if p.returncode:
        raise EmuError("the driver did not build (tests/emu/drv/main.rs against " + str(emu) + "):\n" +
                       (p.stderr or p.stdout)[-3000:])
    exe = d / "target" / "release" / ("emu-drv.exe" if os.name == "nt" else "emu-drv")
    _DRIVER = exe
    return exe


def stage(fw, workdir):
    """copy the package and its ELF (and the source facts the checks read: tests/emu/fwfacts.py) into workdir under
    the fixed family name -> the copied package"""
    fw = Path(fw).resolve()
    elf = fw.with_suffix(".elf")
    if not elf.exists():
        raise EmuError(f"no ELF next to the package: {elf}")
    workdir = Path(workdir)
    workdir.mkdir(parents=True, exist_ok=True)
    dst = workdir / f"{FAMILY}.fwsc"
    shutil.copyfile(fw, dst)
    shutil.copyfile(elf, workdir / f"{FAMILY}.elf")
    return dst


# ---- the flash state (the emulator's FAMILY.nor + FAMILY.index)

def state_dir(workdir):
    return Path(workdir) / "state"


def seed_state(workdir, image, sectors):
    """write a flash state the next session starts from: image (1 MiB), the sectors of it that count"""
    st = state_dir(workdir)
    st.mkdir(parents=True, exist_ok=True)
    assert len(image) == NOR_SIZE
    (st / f"{FAMILY}.nor").write_bytes(bytes(image))
    lines = " ".join(f"{s:#07x}" for s in sorted(sectors))
    (st / f"{FAMILY}.index").write_text(f"{STATE_FORMAT}\n# seeded by tests/emu\nfirmware {FAMILY}.fwsc\n"
                                        f"sectors {lines}\n")


def read_state(workdir):
    """-> the saved flash image (1 MiB, erased where the state holds nothing), or None"""
    p = state_dir(workdir) / f"{FAMILY}.nor"
    return p.read_bytes() if p.exists() else None


# ---- the session

class Emu:
    """a running emulator: Emu(package, workdir, fresh=True, mhz=96). The package must be stage()'s copy (its flash
    state is workdir/state/). Every method waits for the driver's reply; a guest fault raises EmuError"""

    def __init__(self, fw, workdir, fresh=True, mhz=96, log=None):
        env = dict(os.environ)
        if mhz:
            env["FM1_CPU_MHZ"] = str(mhz)
        st = str(state_dir(workdir)) + os.sep
        args = [str(driver()), "--state", st] + (["--fresh"] if fresh else []) + [str(fw)]
        self.p = subprocess.Popen(args, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                                  text=True, env=env, bufsize=1)
        self.err = []
        threading.Thread(target=self._stderr, daemon=True).start()
        self.rows, self.boot, self.log = [], [], log
        while True:
            line = self.p.stdout.readline()
            if not line:
                raise EmuError("the driver stopped at start: " + " | ".join(self.err[-5:]))
            if line.strip() == "ready":
                break
            self.boot.append(line.strip())

    def _stderr(self):
        for line in self.p.stderr:
            self.err.append(line.rstrip())
            del self.err[:-200]

    def cmd(self, c):
        if self.p.poll() is not None:
            raise EmuError(f"the driver is gone ({c})")
        self.p.stdin.write(c + "\n")
        self.p.stdin.flush()
        out = []
        while True:
            line = self.p.stdout.readline()
            if not line:
                raise EmuError(f"the driver stopped on {c}: " + " | ".join(self.err[-5:]))
            line = line.rstrip("\n")
            if line.startswith("H "):
                self.rows.append(line)
            elif line == "ok":
                return out
            elif line.startswith("err "):
                raise EmuError(f"{c}: {line[4:]}")
            else:
                out.append(line)

    # time, keys, knobs
    def run(self, s):
        self.cmd(f"run {s}")

    def align(self):
        self.cmd("align")

    def now(self):
        return float(self.cmd("now")[0])

    def hold(self, *ids):
        self.cmd("hold " + ",".join(map(str, ids)))

    def release(self, *ids):
        self.cmd("release " + ",".join(map(str, ids)) if ids else "release")

    def tap(self, *ids, down=0.12, up=0.25):
        self.hold(*ids)
        self.run(down)
        self.release(*ids)
        self.run(up)

    def turn(self, knob, n):
        """n detents at once, then until the firmware took them"""
        self.cmd(f"turn {knob} {n}")
        self.cmd("settle")

    def click(self, knob, n):
        """n detents one at a time, each settled (+0.25 s)"""
        if n:
            self.cmd(f"click {knob} {n}")

    # memory
    def sym(self, name):
        a, s = self.cmd(f"sym {name}")[0].split()
        return int(a), int(s)

    def has(self, name):
        try:
            self.sym(name)
            return True
        except EmuError:
            return False

    def peek(self, at, n=1):
        return [int(x) for x in self.cmd(f"peek {at} {n}")[0].split()]

    def peekb(self, at, n=1):
        return [int(x) for x in self.cmd(f"peekb {at} {n}")[0].split()]

    def mem(self, at, n):
        """n bytes at a symbol / address as bytes (read as words, little-endian)"""
        w = self.peek(at, (n + 3) // 4)
        return b"".join(x.to_bytes(4, "little") for x in w)[:n]

    def poke(self, at, v):
        self.cmd(f"poke {at} {v}")

    def nor(self, off, n):
        return bytes.fromhex(self.cmd(f"nor {off:#x} {n}")[0])

    def dbg(self):
        return dict(zip(DBG, self.peek("felucca_dbg", len(DBG))))

    # screen, audio
    def png(self, path):
        self.cmd(f"png {path}")

    def lit(self):
        return int(self.cmd("lit")[0])

    def wavstart(self):
        self.cmd("wavstart")

    def wavstop(self, path):
        self.cmd(f"wavstop {path}")
        return read_wav(path)

    # the per-half log
    def log_on(self, *syms):
        self.rows = []
        self.cmd("log on " + " ".join(syms))

    def log_off(self):
        self.cmd("log off")

    def take(self):
        """the H rows since the last take -> [{"t": s, "halves": n, ..., SYM: [words]}]"""
        out = []
        for line in self.rows:
            parts = line.split()
            d = {"t": float(parts[1])}
            for kv in parts[2:]:
                k, v = kv.split("=", 1)
                d[k] = [int(x) for x in v.split(",")] if "," in v or k not in DBG else int(v)
            out.append(d)
        self.rows = []
        return out

    def flush(self):
        return self.cmd("flush")

    def quit(self):
        """save the flash state and stop -> the driver's last lines"""
        out = []
        if self.p.poll() is None:
            try:
                out = self.cmd("quit")
            except EmuError:
                pass
        try:
            self.p.wait(20)
        except subprocess.TimeoutExpired:
            self.p.kill()
        return out

    def close(self):
        """stop without saving (a failed check)"""
        if self.p.poll() is None:
            self.p.kill()
            self.p.wait(10)


def read_wav(path):
    """a 24-bit stereo WAV -> (left, right) as lists of floats (full scale 1.0)"""
    b = Path(path).read_bytes()
    n = struct.unpack("<I", b[40:44])[0] // 6
    d = b[44:44 + n * 6]
    left = [int.from_bytes(d[i:i + 3], "little", signed=True) / 8388608.0 for i in range(0, n * 6, 6)]
    right = [int.from_bytes(d[i + 3:i + 6], "little", signed=True) / 8388608.0 for i in range(0, n * 6, 6)]
    return left, right


def rms(x):
    return (sum(v * v for v in x) / max(1, len(x))) ** 0.5
